# Basic Info from Savas main site
title: Savas
email: info@savaslabs.com
description: >
  A Drupal-centric web development and design shop anchored in Durham, NC.
twitter_username: savas_labs
github_username: savaslabs


# Site settings
baseurl: "" # the subpath of your site, e.g. /blog/
savas_baseurl: "http://www.savaslabs.com"
url: "" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

include:
 - .nojekyll

exclude:
 - "bower_components"
 - "bower.json"
 - "node_modules"
 - "package.json"
 - "js/map_source.js"